---
title: "NY Airbnb"
author: "WenJun(John) Cen"
date: "10/30/2019"
output: html_document
---

```{r setup, include=FALSE}
#Clear All variables & Clear the Screen
rm(list=ls())
cat("\014")

#Read in the Data
airbnb <- read.csv("AB_NYC_2019.csv")


#Explore the data
str(airbnb)
summary(airbnb)

library(tidyverse)
library(neuralnet)
library(MASS)
library(sf)
library(leaflet)
library(tmap) ## Create map and geometry columns
library(tmaptools)
library(ggpubr)

knitr::opts_chunk$set(echo = TRUE)
```

## Data Cleaning
```{r echo=FALSE}
airbnb_separate <- separate(airbnb, col = last_review, into = c("review_year", "review_month", "review_day"),
                            sep = "-") ## Seperate string of date into year, month, and day

airbnb_separate <- replace_na(airbnb_separate, list(review_month = "", review_day = "")) ## Replace NA value with blank
```

## Visualization
```{R}
## Scatterplot on price and # of reviews
air_scatter <- airbnb %>% 
  ggplot(mapping = aes(x = number_of_reviews, y = price, colour = neighbourhood_group)) +
  theme_bw() +
  geom_point() +
  labs(x = "\n# of reviews", y = "Price\n", title = "Reviews Vs. Price Chart\n",
       subtitle = "Airbnb") +
  theme(plot.title = element_text(hjust = 0.5))

## History on which group has highest count
air_his <- airbnb %>%
  mutate(neighbourhood_group = fct_infreq(neighbourhood_group)) %>%
  ggplot(mapping = aes(x = neighbourhood_group))  +
  geom_bar(fill = "light green") +
  labs(x = "\n Neighbourhood Group", y = "Total\n", title = "Neighbourhood Group\n",
       subtitle = "Airbnb") +
  theme(plot.title = element_text(hjust = 0.5))

## Boxplot

air_box <- airbnb %>%
  ggplot(mapping = aes(x = room_type, y = price)) +
  geom_boxplot(aes(colour = neighbourhood_group)) +
  scale_y_continuous(limits = c(0, 350),
                     labels = scales::dollar) +
  labs(x = "Room Type", y = "Price")
  
  ## coord_cartesian(y= c(0, 350)) -- zoom in
  ## scale_y_continuous(limits = c(0, 350)) -- set limits

## ggarrange(air_scatter, air_his, ## put two plots on the same pane
##          ncol = 2, nrow = 1,
##          widths = c(2, 1))
air_scatter
air_his
air_box
```

```{r}

```
